// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
// Run "node scripts/build-registry.js" to regenerate.

import { carbon_teal as professional_carbon_teal } from "./professional/carbon-teal";
import { graphite_blue as professional_graphite_blue } from "./professional/graphite-blue";
import { midnight_indigo as professional_midnight_indigo } from "./professional/midnight-indigo";
import { obsidian_violet as professional_obsidian_violet } from "./professional/obsidian-violet";
import { titanium_gray as professional_titanium_gray } from "./professional/titanium-gray";
import { alabaster_clean as minimal_alabaster_clean } from "./minimal/alabaster-clean";
import { cement_raw as minimal_cement_raw } from "./minimal/cement-raw";
import { quartz_sand as minimal_quartz_sand } from "./minimal/quartz-sand";
import { snow_mono as minimal_snow_mono } from "./minimal/snow-mono";
import { zinc_neutral as minimal_zinc_neutral } from "./minimal/zinc-neutral";
import { consortium_slate as corporate_consortium_slate } from "./corporate/consortium-slate";
import { enterprise_blue as corporate_enterprise_blue } from "./corporate/enterprise-blue";
import { federal_navy as corporate_federal_navy } from "./corporate/federal-navy";
import { mercantile_teal as corporate_mercantile_teal } from "./corporate/mercantile-teal";
import { steel_accent as corporate_steel_accent } from "./corporate/steel-accent";
import { amethyst_glow as purple_amethyst_glow } from "./purple/amethyst-glow";
import { cyber_neon_purple as purple_cyber_neon_purple } from "./purple/cyber-neon-purple";
import { orchid_magic as purple_orchid_magic } from "./purple/orchid-magic";
import { royal_purple as purple_royal_purple } from "./purple/royal-purple";
import { wisteria_soft as purple_wisteria_soft } from "./purple/wisteria-soft";
import { cobalt_electric as blue_cobalt_electric } from "./blue/cobalt-electric";
import { iceberg_arctic as blue_iceberg_arctic } from "./blue/iceberg-arctic";
import { marine_deep as blue_marine_deep } from "./blue/marine-deep";
import { ocean_breeze as blue_ocean_breeze } from "./blue/ocean-breeze";
import { pacific_sky as blue_pacific_sky } from "./blue/pacific-sky";
import { aurora_emerald as green_aurora_emerald } from "./green/aurora-emerald";
import { forest_pine as green_forest_pine } from "./green/forest-pine";
import { jade_classic as green_jade_classic } from "./green/jade-classic";
import { mint_refresh as green_mint_refresh } from "./green/mint-refresh";
import { moss_olive as green_moss_olive } from "./green/moss-olive";
import { amber_glow as warm_amber_glow } from "./warm/amber-glow";
import { bronze_metallic as warm_bronze_metallic } from "./warm/bronze-metallic";
import { peach_sunset as warm_peach_sunset } from "./warm/peach-sunset";
import { sandstone_dune as warm_sandstone_dune } from "./warm/sandstone-dune";
import { terracotta_clay as warm_terracotta_clay } from "./warm/terracotta-clay";
import { lead_coal as neutral_lead_coal } from "./neutral/lead-coal";
import { neutral_gray as neutral_neutral_gray } from "./neutral/neutral-gray";
import { slate_base as neutral_slate_base } from "./neutral/slate-base";
import { stone_warm as neutral_stone_warm } from "./neutral/stone-warm";
import { zinc_base as neutral_zinc_base } from "./neutral/zinc-base";
import { black_white as monochrome_black_white } from "./monochrome/black-white";
import { charcoal_clean as monochrome_charcoal_clean } from "./monochrome/charcoal-clean";
import { obsidian_dark_mono as monochrome_obsidian_dark_mono } from "./monochrome/obsidian-dark-mono";
import { porcelain_white as monochrome_porcelain_white } from "./monochrome/porcelain-white";
import { silver_refined as monochrome_silver_refined } from "./monochrome/silver-refined";
import { cyberpunk_2077 as creative_cyberpunk_2077 } from "./creative/cyberpunk-2077";
import { neon_toxic as creative_neon_toxic } from "./creative/neon-toxic";
import { space_nebula as creative_space_nebula } from "./creative/space-nebula";
import { sunset_strip as creative_sunset_strip } from "./creative/sunset-strip";
import { vintage_retro as creative_vintage_retro } from "./creative/vintage-retro";

import { Palette } from "./types";

export const ALL_PALETTES: Palette[] = [
  professional_carbon_teal,
  professional_graphite_blue,
  professional_midnight_indigo,
  professional_obsidian_violet,
  professional_titanium_gray,
  minimal_alabaster_clean,
  minimal_cement_raw,
  minimal_quartz_sand,
  minimal_snow_mono,
  minimal_zinc_neutral,
  corporate_consortium_slate,
  corporate_enterprise_blue,
  corporate_federal_navy,
  corporate_mercantile_teal,
  corporate_steel_accent,
  purple_amethyst_glow,
  purple_cyber_neon_purple,
  purple_orchid_magic,
  purple_royal_purple,
  purple_wisteria_soft,
  blue_cobalt_electric,
  blue_iceberg_arctic,
  blue_marine_deep,
  blue_ocean_breeze,
  blue_pacific_sky,
  green_aurora_emerald,
  green_forest_pine,
  green_jade_classic,
  green_mint_refresh,
  green_moss_olive,
  warm_amber_glow,
  warm_bronze_metallic,
  warm_peach_sunset,
  warm_sandstone_dune,
  warm_terracotta_clay,
  neutral_lead_coal,
  neutral_neutral_gray,
  neutral_slate_base,
  neutral_stone_warm,
  neutral_zinc_base,
  monochrome_black_white,
  monochrome_charcoal_clean,
  monochrome_obsidian_dark_mono,
  monochrome_porcelain_white,
  monochrome_silver_refined,
  creative_cyberpunk_2077,
  creative_neon_toxic,
  creative_space_nebula,
  creative_sunset_strip,
  creative_vintage_retro
];
