// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
// Run "node scripts/build-component-registry.js" to regenerate.

import { buttonShowcase as buttonShowcase } from "./registry/core/button";
import { avatarShowcase as avatarShowcase } from "./registry/data-display/avatar";
import { badgeShowcase as badgeShowcase } from "./registry/data-display/badge";
import { inputShowcase as inputShowcase } from "./registry/forms/input";

import { ComponentShowcase } from "./types";

export const ALL_COMPONENTS: ComponentShowcase[] = [
  buttonShowcase,
  avatarShowcase,
  badgeShowcase,
  inputShowcase
];
